name: Build and Release Appimage

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  appimage:
    runs-on: ubuntu-latest
    container: "ubuntu:18.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /usr/src/
            /var/cache/apt/
          key: appimage-build-dependencies-cache-${{ github.sha }}
          restore-keys: |
            appimage-build-dependencies-cache-
      - name: Build AppImage
        run: .github/workflows/build_appimage.sh
      - uses: actions/upload-artifact@v3
        with:
          name: qBittorrent-x86_64.AppImage
          path: ".github/workflows/qBittorrent*.AppImage*"
      - name: Upload Github Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ".github/workflows/qBittorrent*.AppImage*"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true